name: ticket_booking_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluentui_icons:
  provider:
  gap:
  flutter_localization:
  intl:
  barcode_widget:
  dio:
  dartz:
  flutter_svg:
  shared_preferences:
  flutter_otp_text_field:
  webview_flutter:
  lottie:
  toastification:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/image/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: DMSerif
      fonts:
        - asset: assets/fonts/DMSerifText-Italic.ttf
        - asset: assets/fonts/DMSerifText-Regular.ttf
          weight: 400
